name: Build SteamVR release

defaults:
  run:
    shell: cmd

on:
  push:
    tags:
      - 'release-*'

jobs:
  build-steamvr-release:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        clean: false

    - name: Unity Build
      run: |
        "C:\Program Files\Unity\Hub\Editor\2021.1.12f1\Editor\Unity.exe" -quit -batchmode -projectPath . -executeMethod FrameSynthesis.XR.Builder.BuildForSteamVR -buildTarget Win64 -logFile -

    - name: Release
      run: |
        xcopy /S /E /I /Y dist\SteamVR C:\Builds\VRSashimiTanpopo\SteamVR\VRSashimiTanpopoRelease${{ github.run_number }}
        robocopy /MIR dist\steamVR C:\bin\steamworks_sdk_151\sdk\tools\ContentBuilder\content
        cd C:\bin\steamworks_sdk_151\sdk\tools\ContentBuilder
        run_build.bat
